Repository glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024-Frontend, pull requests merged in 2024-11, with the labels that each got.

#80 :sparkles: feat: waiter order-tickets page
  package-lock.json
  src/app/modules/waiter/components/navbar/navbar.component.html
  src/app/modules/waiter/pages/order-tickets/order-tickets.component.css
  src/app/modules/waiter/pages/order-tickets/order-tickets.component.html
  src/app/modules/waiter/pages/order-tickets/order-tickets.component.spec.ts
  src/app/modules/waiter/pages/order-tickets/order-tickets.component.ts
  src/app/modules/waiter/waiter-routing.module.ts
  src/app/modules/waiter/waiter.module.ts
Labels: enhancement, M

#83 :sparkles: feat: finish modal products
  src/app/modules/costumer/components/categories/categories.component.html
  src/app/modules/costumer/components/categories/categories.component.ts
  src/app/modules/costumer/components/modal-products/modal-products.component.css
  src/app/modules/costumer/components/modal-products/modal-products.component.html
  src/app/modules/costumer/components/modal-products/modal-products.component.spec.ts
  src/app/modules/costumer/components/modal-products/modal-products.component.ts
  src/app/modules/costumer/costumer.module.ts
  src/app/modules/waiter/components/order-addons/order-addons.component.html
Labels: enhancement, P

#85 :recycle: refactor: Waiter big refactor
  src/app/modules/waiter/components/addon-observation/addon-observation.component.css
  src/app/modules/waiter/components/addon-observation/addon-observation.component.html
  src/app/modules/waiter/components/addon-observation/addon-observation.component.spec.ts
  src/app/modules/waiter/components/addon-observation/addon-observation.component.ts
  src/app/modules/waiter/components/menu-navbar/menu-navbar.component.css
  src/app/modules/waiter/components/menu-navbar/menu-navbar.component.html
  src/app/modules/waiter/components/menu-navbar/menu-navbar.component.spec.ts
  src/app/modules/waiter/components/menu-navbar/menu-navbar.component.ts
  src/app/modules/waiter/components/navbar/navbar.component.html
  src/app/modules/waiter/components/order-addons/order-addons.component.html
  src/app/modules/waiter/components/order-addons/order-addons.component.ts
  src/app/modules/waiter/components/total/total.component.html
  src/app/modules/waiter/components/total/total.component.ts
  src/app/modules/waiter/pages/menu/menu.component.html
  src/app/modules/waiter/pages/order-details/order-details.component.html
  src/app/modules/waiter/pages/order-tickets/order-tickets.component.html
  src/app/modules/waiter/waiter.module.ts
Labels: enhancement, M

#94 :sparkles: feat: Waiter Navigation
  src/app/modules/waiter/components/menu-navbar/menu-navbar.component.html
  src/app/modules/waiter/components/menu-navbar/menu-navbar.component.ts
  src/app/modules/waiter/components/navbar/navbar.component.html
  src/app/modules/waiter/components/total/total.component.html
  src/app/modules/waiter/components/total/total.component.ts
  src/app/modules/waiter/pages/home/home.component.html
  src/app/modules/waiter/pages/menu/menu.component.html
  src/app/modules/waiter/pages/order-tickets/order-tickets.component.html
  src/app/shared/components/menu-item/menu-item.component.html
Labels: enhancement, P

#96 :sparkles: feat: last ajustment
  src/app/modules/costumer/components/categories/categories.component.html
  src/app/modules/costumer/components/modal-products/modal-products.component.html
  src/app/modules/costumer/pages/about-us/about-us.component.html
  src/app/modules/costumer/pages/search/search.component.html
  src/assets/image.png
Labels: enhancement, P

#97 ♻ Refactor: Dashboard linked with navbar
  src/app/app.module.ts
  src/app/modules/admin/admin-routing.module.ts
  src/app/modules/admin/admin.module.ts
  src/app/modules/admin/components/admin-navbar/admin-navbar.component.html
  src/app/modules/admin/components/card-prod-dropdown/card-prod-dropdown.component.html
  src/app/modules/admin/components/card-top-stats/card-top-stats.component.html
  src/app/modules/admin/pages/dashboard/dashboard.component.css
  src/app/modules/admin/pages/dashboard/dashboard.component.html
  src/app/modules/admin/pages/dashboard/dashboard.component.spec.ts
  src/app/modules/admin/pages/dashboard/dashboard.component.ts
Labels: enhancement, P

#98 ✨ feat: Fixed the employees page
  src/app/app.module.ts
  src/app/modules/admin/admin-routing.module.ts
  src/app/modules/admin/admin.module.ts
  src/app/modules/admin/components/admin-navbar/admin-navbar.component.html
  src/app/modules/admin/components/employee-table/employee-table.component.html
  src/app/modules/admin/components/employee-table/employee-table.component.ts
  src/app/modules/admin/pages/employee-register/employee-register.component.html
  src/app/modules/admin/pages/employees/employees.component.css
  src/app/modules/admin/pages/employees/employees.component.html
  src/app/modules/admin/pages/employees/employees.component.spec.ts
  src/app/modules/admin/pages/employees/employees.component.ts
  src/app/modules/admin/pages/squares/squares.component.html
  src/app/prototype/prototype.component.html
Labels: enhancement, P

#100 ♻ Refactor: botton added
  src/app/modules/admin/admin.module.ts
  src/app/modules/admin/components/order-config/order-config.component.css
  src/app/modules/admin/components/order-config/order-config.component.html
  src/app/modules/admin/components/order-config/order-config.component.spec.ts
  src/app/modules/admin/components/order-config/order-config.component.ts
  src/app/modules/admin/pages/restaurant-config/restaurant-config.component.html
Labels: enhancement, P

#102 ✨ feat: Made a shared login component
  src/app/modules/admin/admin-routing.module.ts
  src/app/modules/admin/admin.module.ts
  src/app/modules/admin/pages/employee-register/employee-register.component.html
  src/app/modules/admin/pages/login-admin/login-admin.component.css
  src/app/modules/admin/pages/login-admin/login-admin.component.html
  src/app/modules/admin/pages/login-admin/login-admin.component.spec.ts
  src/app/modules/admin/pages/login-admin/login-admin.component.ts
  src/app/prototype/prototype.component.html
  src/app/shared/components/login/login.component.css
  src/app/shared/components/login/login.component.html
  src/app/shared/components/login/login.component.spec.ts
  src/app/shared/components/login/login.component.ts
  src/app/shared/shared.module.ts
Labels: enhancement, P

#105 :sparkles: feat: Login Navigation
  src/app/modules/waiter/pages/home/home.component.html
  src/app/modules/waiter/pages/login-waiter/login-waiter.component.css
  src/app/modules/waiter/pages/login-waiter/login-waiter.component.html
  src/app/modules/waiter/pages/login-waiter/login-waiter.component.spec.ts
  src/app/modules/waiter/pages/login-waiter/login-waiter.component.ts
  src/app/modules/waiter/waiter-routing.module.ts
  src/app/modules/waiter/waiter.module.ts
  src/app/prototype/prototype.component.html
Labels: enhancement, P

#103 :sparkles: feat: Modal Configuration
  src/app/modules/waiter/components/order-addons/order-addons.component.html
  src/app/modules/waiter/components/order-addons/order-addons.component.ts
  src/app/modules/waiter/components/total/total.component.html
  src/app/modules/waiter/components/total/total.component.ts
  src/app/modules/waiter/pages/home/home.component.html
  src/app/modules/waiter/pages/home/home.component.ts
  src/app/modules/waiter/pages/order-tickets/order-tickets.component.html
  src/app/modules/waiter/pages/order-tickets/order-tickets.component.ts
  src/app/shared/components/modal/modal.component.html
  src/app/shared/components/modal/modal.component.ts
Labels: enhancement, M

#109 :sparkles: feat: Fixed the tables screen
  src/app/modules/admin/admin-routing.module.ts
  src/app/modules/admin/components/admin-navbar/admin-navbar.component.html
  src/app/modules/admin/pages/restaurant-config/restaurant-config.component.html
  src/app/modules/admin/pages/restaurant-config/restaurant-config.component.ts
Labels: enhancement, P

#113 ✨ feat: Added the Squares page
  src/app/modules/admin/admin-routing.module.ts
  src/app/modules/admin/admin.module.ts
  src/app/modules/admin/components/admin-navbar/admin-navbar.component.html
  src/app/modules/admin/components/square-table/square-table.component.css
  src/app/modules/admin/components/square-table/square-table.component.html
  src/app/modules/admin/components/square-table/square-table.component.spec.ts
  src/app/modules/admin/components/square-table/square-table.component.ts
  src/app/modules/admin/pages/squares/squares.component.css
  src/app/modules/admin/pages/squares/squares.component.html
  src/app/modules/admin/pages/squares/squares.component.spec.ts
  src/app/modules/admin/pages/squares/squares.component.ts
Labels: enhancement, P

#116 ✨ feat: Created the about us screen
  package-lock.json
  src/app/app.module.ts
  src/app/modules/admin/admin.module.ts
  src/app/modules/admin/components/about-us-bottom/about-us-bottom.component.css
  src/app/modules/admin/components/about-us-bottom/about-us-bottom.component.html
  src/app/modules/admin/components/about-us-bottom/about-us-bottom.component.spec.ts
  src/app/modules/admin/components/about-us-bottom/about-us-bottom.component.ts
  src/app/modules/admin/components/about-us-middle/about-us-middle.component.css
  src/app/modules/admin/components/about-us-middle/about-us-middle.component.html
  src/app/modules/admin/components/about-us-middle/about-us-middle.component.spec.ts
  src/app/modules/admin/components/about-us-middle/about-us-middle.component.ts
  src/app/modules/admin/components/about-us-upper/about-us-upper.component.css
  src/app/modules/admin/components/about-us-upper/about-us-upper.component.html
  src/app/modules/admin/components/about-us-upper/about-us-upper.component.spec.ts
  src/app/modules/admin/components/about-us-upper/about-us-upper.component.ts
  src/app/modules/admin/components/card-top-stats/card-top-stats.component.html
  src/app/modules/admin/components/js/jquery-1.2.6.pack.js
  src/app/modules/admin/components/js/jquery-3.6.0.min.js
  src/app/modules/admin/components/js/jquery.mask.js
  src/app/modules/admin/components/js/jquery.mask.min.js
  src/app/modules/admin/components/js/jquery.maskedinput-1.1.4.pack.js
  src/app/modules/admin/pages/about-us/about-us.component.html
Labels: enhancement

#122 ✨feat: added code for create and select users
  src/app/app.module.ts
  src/app/interfaces/user.ts
  src/app/modules/admin/admin.module.ts
  src/app/modules/admin/pages/employee-register/employee-register.component.html
  src/app/modules/admin/pages/employee-register/employee-register.component.ts
  src/app/modules/admin/pages/employees/employees.component.html
  src/app/modules/admin/pages/employees/employees.component.ts
  src/app/services/user.service.spec.ts
  src/app/services/user.service.ts
Labels: enhancement

#115 ✨ feat: Changed the squares of the product
  src/app/modules/admin/pages/product/product.component.html
  src/app/modules/admin/pages/product/product.component.ts
  src/app/modules/admin/pages/products/products.component.html
Labels: enhancement, M

#123 ✨ feat: Made the Add and Update Squares
  src/app/interfaces/item.ts
  src/app/interfaces/square.ts
  src/app/modules/admin/admin.module.ts
  src/app/modules/admin/components/square-table/square-table.component.html
  src/app/modules/admin/components/square-table/square-table.component.ts
  src/app/modules/admin/pages/squares/squares.component.html
  src/app/modules/admin/pages/squares/squares.component.ts
  src/app/services/square.service.spec.ts
  src/app/services/square.service.ts
  src/app/shared/components/modal/modal.component.html
  src/app/shared/components/modal/modal.component.ts
Labels: enhancement, M

#125 ✨feat: added POST and PUT items
  src/app/modules/admin/components/square-table/square-table.component.html
  src/app/modules/admin/components/square-table/square-table.component.ts
  src/app/modules/admin/pages/squares/squares.component.html
  src/app/modules/admin/pages/squares/squares.component.ts
  src/app/services/items.service.spec.ts
  src/app/services/items.service.ts
Labels: enhancement, M
