Repository glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024-Frontend, pull requests merged in 2024-12, with the labels that each got.

#126 :sparkles: feat: Services && Interfaces
  src/app/interfaces/product.ts
  src/app/services/product.service.spec.ts
  src/app/services/product.service.ts
Labels: enhancement

#132 :sparkles: feat: added few changes on checkout interface & modal
  src/app/modules/checkout/checkout-routing.module.ts
  src/app/modules/checkout/checkout.module.ts
  src/app/modules/checkout/components/add-cash/add-cash.component.html
  src/app/modules/checkout/components/check-close-register/check-close-register.component.html
  src/app/modules/checkout/components/create-order/create-order.component.html
  src/app/modules/checkout/components/navbar/navbar.component.html
  src/app/modules/checkout/components/remove-tabs/remove-tabs.component.html
  src/app/modules/checkout/components/select-order/select-order.component.html
  src/app/modules/checkout/order-list/order-list.component.css
  src/app/modules/checkout/order-list/order-list.component.html
  src/app/modules/checkout/order-list/order-list.component.spec.ts
  src/app/modules/checkout/order-list/order-list.component.ts
  src/app/modules/checkout/pages/checkout/checkout.component.html
  src/app/modules/checkout/pages/checkout/checkout.component.ts
  src/app/modules/checkout/pages/close-register/close-register.component.html
  src/app/modules/checkout/pages/home/home.component.html
  src/app/modules/checkout/pages/home/home.component.ts
  src/app/modules/checkout/pages/open-register/open-register.component.html
Labels: enhancement, M

#133 ♻ Refactor: Fixed table grid, buttons and about us screen
  src/app/modules/admin/components/admin-navbar/admin-navbar.component.html
  src/app/modules/admin/components/card-top-stats/card-top-stats.component.html
  src/app/modules/admin/components/category-table/category-table.component.html
  src/app/modules/admin/components/square-table/square-table.component.html
  src/app/modules/admin/pages/categories/categories.component.html
  src/app/modules/admin/pages/dashboard/dashboard.component.html
  src/app/modules/admin/pages/product/product.component.html
  src/app/modules/admin/pages/products/products.component.html
  src/app/modules/admin/pages/restaurant-config/restaurant-config.component.html
  src/app/modules/admin/pages/restaurant-config/restaurant-config.component.ts
  src/app/modules/admin/pages/squares/squares.component.html
Labels: enhancement, P

#136 :ok_hand: style: Removed - Change Table
  src/app/modules/waiter/pages/home/home.component.html
  src/app/modules/waiter/pages/home/home.component.ts
Labels: enhancement, invalid, P

#140 :sparkles: feat: added some code on close order page
  src/app/modules/admin/pages/employees/employees.component.html
  src/app/modules/checkout/checkout-routing.module.ts
  src/app/modules/checkout/components/navbar/navbar.component.html
  src/app/modules/checkout/pages/checkout/checkout.component.html
  src/app/modules/checkout/pages/checkout/checkout.component.ts
Labels: enhancement

#141 ✨ feat: integration - backend and frontend
  src/app/interfaces/categories.ts
  src/app/modules/admin/pages/categories/categories.component.html
  src/app/modules/admin/pages/categories/categories.component.ts
  src/app/modules/admin/pages/products/products.component.html
  src/app/modules/admin/pages/products/products.component.ts
  src/app/services/categories.service.spec.ts
  src/app/services/categories.service.ts
  src/app/shared/components/modal/modal.component.html
  src/app/shared/components/modal/modal.component.ts
Labels: enhancement, G

#138 :sparkles: feat: consuming endponit products on waiter module
  src/app/interfaces/product.ts
  src/app/shared/components/menu-item/menu-item.component.html
  src/app/shared/components/menu-item/menu-item.component.ts
Labels: enhancement
