Repository glaucotodesco/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2024-Frontend, pull requests merged in 2024-10, with the labels that each got.

#35 ✨ feat: Added the Products page
  package-lock.json
  src/app/app.module.ts
  src/app/modules/admin/admin-routing.module.ts
  src/app/modules/admin/admin.module.ts
  src/app/modules/admin/components/category-table/category-table.component.css
  src/app/modules/admin/components/category-table/category-table.component.html
  src/app/modules/admin/components/category-table/category-table.component.spec.ts
  src/app/modules/admin/components/category-table/category-table.component.ts
  src/app/modules/admin/pages/products/products.component.css
  src/app/modules/admin/pages/products/products.component.html
  src/app/modules/admin/pages/products/products.component.spec.ts
  src/app/modules/admin/pages/products/products.component.ts
Labels: enhancement, P

#41 :sparkles: feat: added template for order list
  angular.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/modules/checkout/checkout-routing.module.ts
  src/app/modules/checkout/checkout.module.ts
  src/app/modules/checkout/order-list/order-list.component.css
  src/app/modules/checkout/order-list/order-list.component.html
  src/app/modules/checkout/order-list/order-list.component.spec.ts
  src/app/modules/checkout/order-list/order-list.component.ts
Labels: enhancement, P

#42 :sparkles: feat: Fixed some stuff from template
  src/app/app.component.html
  src/app/app.module.ts
  src/app/modules/checkout/checkout-routing.module.ts
  src/app/modules/checkout/checkout.module.ts
  src/app/modules/checkout/pages/checkout/checkout.component.css
  src/app/modules/checkout/pages/checkout/checkout.component.html
  src/app/modules/checkout/pages/checkout/checkout.component.spec.ts
  src/app/modules/checkout/pages/checkout/checkout.component.ts
Labels: enhancement, M

#43 :sparkles: feat: waiter menu page
  .nvmrc
  angular.json
  src/app/modules/waiter/pages/menu/menu.component.html
  src/app/modules/waiter/waiter-routing.module.ts
  src/app/modules/waiter/waiter.module.ts
  src/app/shared/components/menu-item/menu-item.component.css
  src/app/shared/components/menu-item/menu-item.component.html
  src/app/shared/components/menu-item/menu-item.component.spec.ts
  src/app/shared/components/menu-item/menu-item.component.ts
  src/app/shared/shared.module.ts
Labels: enhancement, M

#44 :sparkles: feat: waiter order-details page
  src/app/modules/waiter/components/navbar/navbar.component.css
  src/app/modules/waiter/components/navbar/navbar.component.html
  src/app/modules/waiter/components/navbar/navbar.component.spec.ts
  src/app/modules/waiter/components/navbar/navbar.component.ts
  src/app/modules/waiter/components/order-addons/order-addons.component.css
  src/app/modules/waiter/components/order-addons/order-addons.component.html
  src/app/modules/waiter/components/order-addons/order-addons.component.spec.ts
  src/app/modules/waiter/components/order-addons/order-addons.component.ts
  src/app/modules/waiter/components/total/total.component.css
  src/app/modules/waiter/components/total/total.component.html
  src/app/modules/waiter/components/total/total.component.spec.ts
  src/app/modules/waiter/components/total/total.component.ts
  src/app/modules/waiter/pages/home/home.component.html
  src/app/modules/waiter/pages/order-details/order-details.component.css
  src/app/modules/waiter/pages/order-details/order-details.component.html
  src/app/modules/waiter/pages/order-details/order-details.component.spec.ts
  src/app/modules/waiter/pages/order-details/order-details.component.ts
  src/app/modules/waiter/waiter-routing.module.ts
  src/app/modules/waiter/waiter.module.ts
Labels: enhancement, G

#48 ✨ feat: Made the product screen
  src/app/modules/admin/admin.module.ts
  src/app/modules/admin/components/category-table/category-table.component.html
  src/app/modules/admin/components/category-table/category-table.component.ts
  src/app/modules/admin/pages/categories/categories.component.html
  src/app/modules/admin/pages/product/product.component.css
  src/app/modules/admin/pages/product/product.component.html
  src/app/modules/admin/pages/product/product.component.spec.ts
  src/app/modules/admin/pages/product/product.component.ts
  src/app/modules/admin/pages/products/products.component.html
  src/app/modules/admin/pages/products/products.component.ts
Labels: enhancement, M

#54 ✨ feat: conclusion of aboutUs prototipation
  src/app/modules/costumer/costumer-routing.module.ts
  src/app/modules/costumer/costumer.module.ts
  src/app/modules/costumer/pages/about-us/about-us.component.css
  src/app/modules/costumer/pages/about-us/about-us.component.html
  src/app/modules/costumer/pages/about-us/about-us.component.spec.ts
  src/app/modules/costumer/pages/about-us/about-us.component.ts
  src/assets/ImagemRest.jpg
Labels: enhancement, P

#62 ✨ feat: Added the login screen for Admin
  src/app/modules/admin/admin-routing.module.ts
  src/app/modules/admin/admin.module.ts
  src/app/modules/admin/pages/login/login.component.css
  src/app/modules/admin/pages/login/login.component.html
  src/app/modules/admin/pages/login/login.component.spec.ts
  src/app/modules/admin/pages/login/login.component.ts
Labels: enhancement, P

#68 ✨ feat: Added the Navbar
  src/app/modules/admin/admin-routing.module.ts
  src/app/modules/admin/admin.module.ts
  src/app/modules/admin/components/admin-navbar/admin-navbar.component.css
  src/app/modules/admin/components/admin-navbar/admin-navbar.component.html
  src/app/modules/admin/components/admin-navbar/admin-navbar.component.spec.ts
  src/app/modules/admin/components/admin-navbar/admin-navbar.component.ts
  src/app/modules/admin/components/category-table/category-table.component.html
  src/app/modules/admin/pages/categories/categories.component.html
  src/app/modules/admin/pages/home/home.component.html
  src/app/modules/admin/pages/products/products.component.html
Labels: enhancement, P

#69 ✨ feat: Added Module Navigation
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/modules/checkout/checkout-routing.module.ts
  src/app/modules/checkout/checkout.module.ts
  src/app/modules/waiter/pages/home/home.component.html
  src/app/prototype/prototype.component.css
  src/app/prototype/prototype.component.html
  src/app/prototype/prototype.component.spec.ts
  src/app/prototype/prototype.component.ts
Labels: enhancement, P

#72 ✨ feat: Added employee register page
  src/app/modules/admin/admin-routing.module.ts
  src/app/modules/admin/admin.module.ts
  src/app/modules/admin/pages/employee-register/employee-register.component.css
  src/app/modules/admin/pages/employee-register/employee-register.component.html
  src/app/modules/admin/pages/employee-register/employee-register.component.spec.ts
  src/app/modules/admin/pages/employee-register/employee-register.component.ts
Labels: enhancement, M

#46 ✨ feat: Implementation of the Side Menu Component
  src/app/modules/costumer/components/side-menu/side-menu.component.css
  src/app/modules/costumer/components/side-menu/side-menu.component.html
  src/app/modules/costumer/components/side-menu/side-menu.component.spec.ts
  src/app/modules/costumer/components/side-menu/side-menu.component.ts
  src/app/modules/costumer/costumer-routing.module.ts
  src/app/modules/costumer/costumer.module.ts
  src/app/modules/costumer/pages/main/main.component.css
  src/app/modules/costumer/pages/main/main.component.html
  src/app/modules/costumer/pages/main/main.component.spec.ts
  src/app/modules/costumer/pages/main/main.component.ts
Labels: enhancement, P

#31 ✨ feat: Added some router stuff
  src/app/app-routing.module.ts
  src/app/modules/checkout/checkout-routing.module.ts
  src/app/modules/checkout/checkout.module.ts
  src/app/modules/checkout/components/add-cash/add-cash.component.css
  src/app/modules/checkout/components/add-cash/add-cash.component.html
  src/app/modules/checkout/components/add-cash/add-cash.component.spec.ts
  src/app/modules/checkout/components/add-cash/add-cash.component.ts
  src/app/modules/checkout/components/create-order/create-order.component.css
  src/app/modules/checkout/components/create-order/create-order.component.html
  src/app/modules/checkout/components/create-order/create-order.component.spec.ts
  src/app/modules/checkout/components/create-order/create-order.component.ts
  src/app/modules/checkout/components/order-register/order-register.component.css
  src/app/modules/checkout/components/order-register/order-register.component.html
  src/app/modules/checkout/components/order-register/order-register.component.spec.ts
  src/app/modules/checkout/components/order-register/order-register.component.ts
  src/app/modules/checkout/components/select-order/select-order.component.css
  src/app/modules/checkout/components/select-order/select-order.component.html
  src/app/modules/checkout/components/select-order/select-order.component.spec.ts
  src/app/modules/checkout/components/select-order/select-order.component.ts
  src/app/modules/checkout/pages/home/home.component.css
  src/app/modules/checkout/pages/home/home.component.html
  src/app/modules/checkout/pages/home/home.component.ts
  src/app/shared/components/modal/modal.component.html
Labels: enhancement

#75 ✨ feat: Fixed the routes of prototype, admin and checkout
  src/app/modules/admin/admin-routing.module.ts
  src/app/modules/checkout/checkout-routing.module.ts
  src/app/prototype/prototype.component.html
Labels: enhancement, P

#76 :sparkles: upgrade tabs
  src/app/modules/costumer/components/side-menu/side-menu.component.html
  src/app/modules/costumer/components/side-menu/side-menu.component.ts
  src/app/modules/costumer/pages/about-us/about-us.component.html
  src/app/modules/costumer/pages/home/home.component.html
  src/app/modules/costumer/pages/main/main.component.html
  src/app/modules/costumer/pages/search/search.component.html
  src/app/modules/costumer/pages/search/search.component.ts
Labels: enhancement
